# Generated by Django 5.0 on 2025-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_pro',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('pc', 'PC')], default='', max_length=20),
        ),
    ]
