# Generated by Django 5.0 on 2025-02-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_type_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_pro',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('pc', 'PC')], default='todo', max_length=20),
        ),
    ]
